### ISSUE TITLE
fix: some users can't be found

### ISSUE THREAD

**Issue by Reaster0** [42Atomys/stud42#308]
### Describe the bug

there is some users that i can't add as friends because i can't find them

### To Reproduce

try to add cchicote or alkanaev or gperez as friends

### Expected behavior

found the users as intended

### Version of software

v1.0.1

### Environment

Live (https://s42.app)

### Additional context

it seems that the common traits for theses users is that they havent log since 7month or more, users logged in 6month work fine but beside 7month it seems that they can't be found

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Atomys** [comment]
hi @Reaster0, thanks for your contribution and your issue. 

The login you give dont exist on our database. 

Due to the RGPD, and 42network rules, some student cannot be found for the following reason : 

> Users/students can only be found on the https://s42.app system after their first connection to the cluster. The automatic import during the search is no longer done to comply with the new rules. 

And yes you right, the "production" of s42.app have 7 months, so every students how logged in cluster since 7 months are in database. 

**The solution / workaround to be legal and found your friend on s42 : Ask to your friend to login on https://s42.app** 

We try to found a solution to be legal for 42 network and RGPD compliant, actually this is the only solution we found. Feels free to give ideas, or feedback. I totally understand your frustration about this.

**Comment by Reaster0** [comment]
Ho well if we can't do that much about it, i'll will not be frustrated by that haha ;) 
Case closed.

**Comment by 42Atomys** [comment]
Thanks for your answer, I close the issue :)
